#!/bin/bash

set -e

h="https://sip.dev.mconf.com"
r="Virtual Office Hours - Michael Bailetti"
b=1
w=10000
l=60000

usage() {
  echo "Usage: $0"
  echo "  -h host  server url         default: https://sip.dev.mconf.com"
  echo "  -b bots  number of bots     default: 1"
  echo "  -w wait  time between bots  default: 10000 (10 seconds)"
  echo "  -l life  bot life span      default: 60000 (60 seconds)"
  exit 1
}

# Gather run arguments
while getopts ":h:b:w:l:" o; do
  case "${o}" in
    h)
      h=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    w)
      w=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

echo "Copying test script..."
cp -rf /tmp/scripts/join.js /tmp/script.js

echo "Setting test variables..."
sed -e "s,HOST,\"$h\",g" -i /tmp/script.js
echo "Host: $h"
sed -e "s,ROOM,\"$r\",g" -i /tmp/script.js
echo "Room: $r"
sed -e "s,BOTS,$b,g" -i /tmp/script.js
echo "Bots: $b"
sed -e "s,WAIT,$w,g" -i /tmp/script.js
echo "Wait: $w"
sed -e "s,LIFE,$l,g" -i /tmp/script.js
echo "Life: $l"

echo "Running Docker..."
sudo docker run -i --rm --cap-add=SYS_ADMIN --name puppeteer-flash puppeteer-flash:latest xvfb-run -a node -e "`cat /tmp/script.js`"
