#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install -y curl

# Installing Node
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get update
sudo apt-get install -y nodejs

# Copying mconfless script
cp hooks/run /tmp
sudo chmod +x /tmp/run

# Copying bigbluebot scripts
cp -r utils/mconfless /tmp
cd /tmp/mconfless
npm install
