#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install -y curl

# Installing Node
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo bash nodesource_setup.sh
sudo apt-get update
sudo apt-get install -y nodejs

# Copying mconfless script
cp hooks/run ~/
sudo chmod +x ~/run

# Copying bigbluebot scripts
cp -r utils/mconfless ~/
cd ~/mconfless
npm install