#!/bin/bash

set -e

export JUJU_USER=ubuntu
export JUJU_HOME=/home/$JUJU_USER

npm install $JUJU_HOME/mconfless

t="join"
h="https://test-live220.dev.mconf.com"
r="Demo Meeting"
b=1
p=1
w=2000
l=60000

usage() {
  echo "Usage: $0"
  echo "  -t test  test script        default: join"
  echo "  -h host  server url         default: https://test-live220.dev.mconf.com"
  echo "  -r room  room name          default: \"Demo Meeting\""
  echo "  -b bots  number of bots     default: 1"
  echo "  -p pool  browsers pool      default: 1"
  echo "  -w wait  time between bots  default: 2000 (2 seconds)"
  echo "  -l life  bot life span      default: 60000 (60 seconds)"
  exit 1
}

# Gather run arguments
while getopts ":t:h:r:b:p:w:l:" o; do
  case "${o}" in
    t)
      t=${OPTARG}
      ;;
    h)
      h=${OPTARG}
      ;;
    r)
      r=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    p)
      p=${OPTARG}
      ;;
    w)
      w=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

echo "Setting variables..."
export BIGBLUEBOT_HOST=$h
echo "Host: $h"
export BIGBLUEBOT_ROOM=$r
echo "Room: $r"
export BIGBLUEBOT_BOTS=$b
echo "Bots: $b"
export BIGBLUEBOT_POOL=$p
echo "Pool: $p"
export BIGBLUEBOT_WAIT=$w
echo "Wait: $w"
export BIGBLUEBOT_LIFE=$l
echo "Life: $l"

echo "Running..."
nodejs $JUJU_HOME/mconfless/$t
