#!/bin/bash

set -e

# Installing Docker Engine
sudo apt-get update
sudo apt-get install --no-install-recommends \
  apt-transport-https \
  curl \
  software-properties-common

curl -fsSL 'https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | sudo apt-key add -

sudo add-apt-repository \
  "deb https://packages.docker.com/1.13/apt/repo/ \
  ubuntu-$(lsb_release -cs) \
  main"

sudo apt-get update
sudo apt-get -y install docker-engine

sudo docker pull justinribeiro/chrome-headless
sudo docker run -d -p 9222:9222 --cap-add=SYS_ADMIN justinribeiro/chrome-headless

# Installing Node
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get update
sudo apt-get install nodejs

# Copying run script
cp hooks/run /tmp
chmod +x /tmp/run

# Copying test scripts
cp -r utils/mconfless /tmp
