#!/bin/bash

set -e

# Installing Docker Engine
sudo apt-get update
sudo apt-get install --no-install-recommends \
  apt-transport-https \
  curl \
  software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"

sudo apt-get update
sudo apt-get -y install docker-ce docker-ce-cli containerd.io

# To run docker without sudo:
#  sudo usermod -aG docker ubuntu
#  sudo su - ubuntu

# When trying to run it locally, this might help:
# https://stackoverflow.com/questions/45731683/docker-pull-operation-not-permitted
#  sudo systemctl stop docker
#  echo "{\"storage-driver\": \"overlay\"}" | sudo tee /etc/docker/daemon.json
#  sudo systemctl start docker

sudo docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
sudo docker pull mconf/puppeteer:html5

# Copying run script
cp hooks/run /tmp
chmod +x /tmp/run

# Copying test scripts
cp -r utils/scripts /tmp
