#!/bin/bash

set -e

p="/home/ubuntu/mconfless/join.js"
h="https://html5.dev.mconf.com"
r="Test Room"
b=1
w=2000
l=60000

usage() {
  echo "Usage: $0"
  echo "  -p path"
  echo "  -h host  server url         default: https://html5.dev.mconf.com"
  echo "  -r room  room name          default: \"Test Room\""
  echo "  -b bots  number of bots     default: 1"
  echo "  -w wait  time between bots  default: 2000 (2 seconds)"
  echo "  -l life  bot life span      default: 60000 (60 seconds)"
  exit 1
}

# Gather run arguments
while getopts ":p:h:r:b:w:l:" o; do
  case "${o}" in
    p)
      p=${OPTARG}
      ;;
    h)
      h=${OPTARG}
      ;;
    r)
      r=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    w)
      w=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

export BIGBLUEBOT_BROWSER=google-chrome

echo "Setting test variables..."
export BIGBLUEBOT_HOST=$h
echo "Host: $h"
export BIGBLUEBOT_ROOM=$r
echo "Room: $r"
export BIGBLUEBOT_BOTS=$b
echo "Bots: $b"
export BIGBLUEBOT_WAIT=$w
echo "Wait: $w"
export BIGBLUEBOT_LIFE=$l
echo "Life: $l"

echo "Running..."
node $p
