#!/bin/bash

set -e

t="join"
h="https://html5.dev.mconf.com"
r="Test Room"
b=1
w=2000
l=60000

usage() {
  echo "Usage: $0"
  echo "  -t test"
  echo "           lis"
  echo "           mic"
  echo "           cam"
  echo "           all"
  echo "           msg"
  echo "           pad"
  echo "  default: join"
  echo "  -h host  server url         default: https://html5.dev.mconf.com"
  echo "  -r room  room name          default: \"Test Room\""
  echo "  -b bots  number of bots     default: 1"
  echo "  -w wait  time between bots  default: 2000 (2 seconds)"
  echo "  -l life  bot life span      default: 60000 (60 seconds)"
  exit 1
}

# Gather run arguments
while getopts ":t:h:r:b:w:l:" o; do
  case "${o}" in
    t)
      t=${OPTARG}
      ((t == "lis" || t == "mic" || t == "cam" || t == "msg" || t == "pad" || t == "all")) || usage
      ;;
    h)
      h=${OPTARG}
      ;;
    r)
      r=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    w)
      w=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

echo "Copying config file..."
cp -rf /tmp/scripts/conf/config.json.template /tmp/scripts/conf/config.json

echo "Setting test variables..."
sed -e "s,HOST,\"$h\",g" -i /tmp/scripts/conf/config.json
echo "Host: $h"
sed -e "s,ROOM,\"$r\",g" -i /tmp/scripts/conf/config.json
echo "Room: $r"
sed -e "s,BOTS,$b,g" -i /tmp/scripts/conf/config.json
echo "Bots: $b"
sed -e "s,WAIT,$w,g" -i /tmp/scripts/conf/config.json
echo "Wait: $w"
sed -e "s,LIFE,$l,g" -i /tmp/scripts/conf/config.json
echo "Life: $l"

DOCKER_CMD="sudo docker run -i --rm -v /tmp:/tmp --cap-add=SYS_ADMIN mconf/puppeteer:html5 node"

echo "Running Docker..."
case $t in
  lis)
    echo "Starting listen only test"
    $DOCKER_CMD /tmp/scripts/listen-only.js
    ;;
  mic)
    echo "Starting audio test"
    $DOCKER_CMD /tmp/scripts/audio.js
    ;;
  cam)
    echo "Starting video test"
    $DOCKER_CMD /tmp/scripts/video.js
    ;;
  all)
    echo "Starting audio and video test"
    $DOCKER_CMD /tmp/scripts/audio-and-video.js
    ;;
  msg)
    echo "Starting chat test"
    $DOCKER_CMD /tmp/scripts/chat.js
    ;;
  pad)
    echo "Starting note test"
    $DOCKER_CMD /tmp/scripts/note.js
    ;;
  *)
    echo "Starting join test"
    $DOCKER_CMD /tmp/scripts/kurento.js
    ;;
esac
