#!/bin/bash

set -e

t="listen-only"
h="https://html5.dev.mconf.com"
b=1
w=2000
l=60000

usage() {
  echo "Usage: $0"
  echo "  -t test  <mic|cam|all>      default: listen-only"
  echo "  -h host  server url         default: https://html5.dev.mconf.com"
  echo "  -b bots  number of bots     default: 1"
  echo "  -w wait  time between bots  default: 2000 (2 seconds)"
  echo "  -l life  bot life span      default: 60000 (60 seconds)"
  exit 1
}

# Gather run arguments
while getopts ":t:h:b:w:l:" o; do
  case "${o}" in
    t)
      t=${OPTARG}
      ((t == "mic" || t == "cam" || t == "all")) || usage
      ;;
    h)
      h=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    w)
      w=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

# Copy test script
case $t in
  mic)
    cp -rf /tmp/scripts/audio.js /tmp/script.js
    ;;
  cam)
    cp -rf /tmp/scripts/video.js /tmp/script.js
    ;;
  all)
    cp -rf /tmp/scripts/audio-and-video.js /tmp/script.js
    ;;
  *)
    cp -rf /tmp/scripts/listen-only.js /tmp/script.js
    ;;
esac

sed -e "s,HOST,\"$h\",g" -i /tmp/script.js
sed -e "s,BOTS,$b,g" -i /tmp/script.js
sed -e "s,WAIT,$w,g" -i /tmp/script.js
sed -e "s,LIFE,$l,g" -i /tmp/script.js

sudo docker run -i --rm --cap-add=SYS_ADMIN --name puppeteer mconftec/puppeteer:firsttry node -e "`cat /tmp/script.js`"
