#!/bin/bash

set -x

MONITOR_SCRIPT=$PWD/utils/bbb-live-monitor/monitor.sh
DSTAT_SCRIPT=$PWD/utils/bbb-live-monitor/dstat.sh

NGINX_LOG_PATH=/var/log/nginx/html5-client.logs

BIN_PATH=$PWD/hooks
SUITES_PATH=$PWD/suites

LOG_PATH=$PWD/logs

usage() {
  echo "Usage: $0"
  exit 1
}

# Gather run arguments
while getopts ":t:" o; do
  case "${o}" in
    a)
      a="TRUE"
      ;;
    s)
      s=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

START_DATE=$(date +%F-%H-%M-%S)
SUITE_DIR="$LOG_PATH/$START_DATE"-suites

echo "Starting new test suite $SUITE_DIR"

mkdir -p $SUITE_DIR
cd $SUITE_DIR

function getSuites() {
  cd $SUITES_PATH && ls
}

function normalizeNGINXLogs() {
  cat $NGINX_LOG_PATH | sed 's/\\x22/"/g' | sed 's/\\x5C//g' > $1
}

function suite() {

  # Delete current NGINX logs
  sudo truncate -s0 $NGINX_LOG_PATH

  mkdir $SUITE_DIR/$1 -p
  cd $SUITE_DIR/$1

  $MONITOR_SCRIPT > /dev/null &
  MONITOR_PID=$!
  $DSTAT_SCRIPT > /dev/null &
  DSTAT_PID=$!

  $SUITES_PATH/$suite $BIN_PATH

  sleep 2;
  normalizeNGINXLogs $SUITE_DIR/$1/html5-client.log

  kill $MONITOR_PID
  kill $DSTAT_PID
}

for suite in $(getSuites); do
  suite $suite
done;

